name: lint checker

on:
  push:
    branches:
      - 'github-actions-test-lint'

jobs:
  eslint:
    name: check_eslint_error
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/**/*.{vue,ts,js}'

